IllexForest_Text_Cesar_1::
    .string "¡Dichosos fantasmas!\n"
    .string "¡El más grande me ha robado mi\l"
    .string "Pokéball especial!\p"
    .string "Disculpa, me llamo César y soy\n"
    .string "un fabricante artesanal de\l"
    .string "Pokéballs.\p"
    .string "Había fabricado una Pokéball\n"
    .string "especial para honrar al\l"
    .string "Guardián del Encinar, ¡pero ese\l"
    .string "fantasma me la ha robado!$"

IllexForest_Text_Cesar_2::
    .string "Perdón, no quería aburrirte con mis\n"
    .string "historias…\p"
    .string "El Guardián siempre se muestra\n"
    .string "agradecido con quien libera el Encinar\l"
    .string "de los malos espíritus.$"

IllexForest_Text_Cesar_3::
    .string "¿Tus Pokémon necesitan un descanso?$"

IllexForest_Text_Cesar_4::
    .string "Muy bien, ten cuidado por el bosque.$"

IllexForest_Text_Cesar_5::
    .string "¡Oh, veo que tienes mi Pokéball!\n"
    .string "¿Por qué no se la presentas al\l"
    .string "guardián?$"

IllexForest_Text_Gastly_1::
    .string "¡Quiero… devorar tu ser!$"

IllexForest_Text_Gastly_2::
    .string "¡Presiento… tu oscuridad!$"

IllexForest_Text_Gastly_3::
    .string "Mmm… tu aura… es…$"

IllexForest_Text_Gastly_4::
    .string "Solo veo… tu perdición…$"

IllexForest_Text_Gastly_5::
    .string "…………… hambre…$"

IllexForest_Text_Haunter::
    .string "¡Voy a consumir… tu alma!$"

IllexForest_Text_Gengar_1::
    .string "Es gracioso…\n"
    .string "Tú quieres objeto detrás de mí.\p"
    .string "Pero yo no dartelo sin más.\n"
    .string "Muy gracioso…$"

IllexForest_Text_Gengar_2::
    .string "Tú no reír…\n"
    .string "Tú no ganar todavía…\p"
    .string "Perteneces a mí… pero aún\n"
    .string "no sabes…$"

IllexForest_Text_Gengar_3::
    .string "¡Ja ja ja ja ja ja!$"

IllexForest_Text_Karateka_1::
    .string "Uno de los Farfetch’d que\n"
    .string "ayudan a talar madera para hacer\l"
    .string "carbón vegetal ha huído\l"
    .string "despavorido por los fantasmas.$"

IllexForest_Text_Farfetchd_1::
    .string "¿Farf?$"

IllexForest_Text_Cartel::
    .string "Hay tantos árboles en el Encinar\n"
    .string "que no se ve ni el cielo.\p"
    .string "Por favor, busca objetos que\n"
    .string "puedan haber caído.$"

IllexForest_Text_Celebi_NoGsBall::
    .string "Santuario del Encinar…\n"
    .string "Construido en honor del guardián\l"
    .string "del bosque…$"

IllexForest_Text_Celebi_UseGsBall::
    .string "Parece que hay una muesca…\n"
    .string "¡La GS Ball encaja perfectamente!\p"
    .string "{PLAYER} colocó la GS Ball en la\n"
    .string "muesca.$"

IllexForest_Text_Celebi_SendHome::
    .string "¡Celebi te lleva a casa como\n"
    .string "agradecimiento por liberar de los\l"
    .string "espíritus al Encinar!$"