IllexForest_Text_Cesar_1::
    .string "¡Dichosos fantasmas!\n"
    .string "¡El más grande me ha robado mi\l"
    .string "Pokéball especial!\p"
    .string "Disculpa, me llamo César y soy\n"
    .string "un fabricante artesanal de\l"
    .string "Pokéballs.\p"
    .string "Había fabricado una Pokéball\n"
    .string "especial para honrar al\l"
    .string "guardian del Encinar, ¡pero ese\l"
    .string "fantasma me la ha robado!$"

IllexForest_Text_Cesar_2::
    .string "Perdón, no quería aburrirte con mis\n"
    .string "historias…\n"

IllexForest_Text_Cesar_3::
    .string "¿Tus Pokémon necesitan un descanso?$"

IllexForest_Text_Cesar_4::
    .string "Muy bien, ten cuidado por el bosque.$"

IllexForest_Text_Gastly_1::
    .string "¡Quiero… devorar tu ser!$"

IllexForest_Text_Gastly_2::
    .string "¡Presiento… tu oscuridad!$"

IllexForest_Text_Gastly_3::
    .string "Mmm… tu aura… es…$"

IllexForest_Text_Gastly_4::
    .string "Solo veo… tu perdición…$"

IllexForest_Text_Gastly_5::
    .string "…………… hambre…$"

IllexForest_Text_Haunter::
    .string "¡Voy a consumir… tu alma!$"

IllexForest_Text_Karateka_1::
    .string "Uno de los Farfetch’d que\n"
    .string "ayudan a talar madera para hacer\l"
    .string "carbón vegetal ha huído\l"
    .string "despavorido por los fantasmas.$"

IllexForest_Text_Farfetchd_1::
    .string "¿Farf?$"

IllexForest_Text_Cartel::
    .string "Hay tantos árboles en el Encinar\n"
    .string "que no se ve ni el cielo.\p"
    .string "Por favor, busca objetos que\n"
    .string "puedan haber caído.$"