PokemonTower_7F_Text_Grunt1Intro::
    .string "What do you want?\n"
    .string "Why are you here?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "I give up!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "I'm not going to forget this!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "This old guy marched right up to\n"
    .string "our HIDEOUT.\p"
    .string "Then, he starts ranting about how\n"
    .string "TEAM ROCKET's abusing POKéMON.\p"
    .string "So, we're just talking it over as\n"
    .string "adults.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Please!\n"
    .string "No more!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "POKéMON are only good for making\n"
    .string "money. Why not use them?\p"
    .string "You stay out of our business!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "You're not saving anyone, kid!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Don't fight us ROCKETS!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "You're not getting away with this!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "¡Ah! ¡{PLAYER}!\p"
    .string "Cuando desapareciste con toda\n"
    .string "esa luz aparecieron un montón de\l"
    .string "fantasmas y cuando me dí cuenta,\l"
    .string "había aparecido aquí.$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe_2::
    .string "¿Has oído eso?\p"
    .string "¡Te han seguido!\n"
    .string "¡Tienes que huir!\p"
    .string "¡Esto te permitirá enfrentarte\n"
    .string "a los fantasmas!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe_3::
    .string "¡Noooooo!$"

PokemonTower_7F_Text_EvilGhost::
    .string "¡{PLAYER}!\p"
    .string "¡Ven a buscarme!\n"
    .string "¡Te espero al final!$"

PokemonTower_7F_Text_Ghost::
    .string "Debes salvar al pueblo…\n"
    .string "Rescata al Sr. Fuji…$"