PokemonTower_4F_Text_PaulaIntro::
    .string "¡Espíritus! ¡No!\n"
    .string "¡Kwaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "¿Dónde ha ido?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Esto debe ser un sueño…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "¡Únete a nosotros!\n"
    .string "¡Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "¿Qué?$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "Los espíritus no se dejan\n"
    .string "ver…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu…\n"
    .string "¡Somos invencibles!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "¿Um?\n"
    .string "¿Qué ha pasado?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Que los difuntos descansen\n"
    .string "en paz…$"

