LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "Con esta crisis se están agotando\n"
    .string "las existencias.$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "Ni un REVIVIR podría resucitar\n"
    .string "las almas que nos acechan.$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "De momento parece que los fantasmas\n"
    .string "no van a entrar aquí.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
