gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "Los botones se explicarán por\n"
    .string "orden de importancia.$"

gControlsGuide_Text_DPad::
    .string "Mueve al protagonista.\n"
    .string "Se usa para desplazarte por\n"
    .string "los menús.$"

gControlsGuide_Text_AButton::
    .string "Se usa para aceptar, interactuar\n"
    .string "con objetos, conversar y leer.$"

gControlsGuide_Text_BButton::
    .string "Se usar para salir o cancelar.$"

gControlsGuide_Text_StartButton::
    .string "Pulsa este botón para abrir el\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Se usa para ordenar objetos y\n"
    .string "usar un objeto registrado.$"

gControlsGuide_Text_LRButtons::
    .string "Si necesitas ayuda con el juego\n"
    .string "pulsa los botones L o R.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Cuéntame. ¿Eres chico?\n"
    .string "¿O eres chica?$"

gPikachuIntro_Text_Page1::
    .string "En el mundo al que estás a punto de\n"
    .string "entrar, te embarcarás en una gran\n"
    .string "aventura en la que serás protagonista.\n"
    .string "\n"
    .string "Habla con la gente y comprueba\n"
    .string "lo que ocurre donde vayas,\n"
    .string "ya sean pueblos, rutas o cuevas.\n"
    .string "Busca pistas por todas partes.$\n"

gPikachuIntro_Text_Page2::
    .string "Se abrirán nuevos caminos ayudando\n"
    .string "a los personajes, superando desafíos\n"
    .string "y resolviendo misterios.\n"
    .string "\n"
    .string "A veces, otros te desafiarán\n"
    .string "y te atacarán criaturas salvajes.\n"
    .string "Sé valiente y sigue adelante.$"

gPikachuIntro_Text_Page3::
    .string "Recuerda, habla con todo el mundo,\n"
    .string "crecerás como persona, y ese es\n"
    .string "tu principal objetivo.\n"
    .string "\n"
    .string "Pulsa el botón A y…\n"
    .string "¡que comience la aventura!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "¡Hola!\n"
    .string "¡Encantado de conocerte!\p"
    .string "¡Bienvenido al mundo de POKéMON!\p"
    .string "Mi nombre es OAK.\p"
    .string "Pero la gente se refiere a mí\n"
    .string "como el PROFESOR POKéMON.\p$"

gOakSpeech_Text_ThisWorld::
    .string "¡Este mundo está…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…habitado por unas criaturas\n"
    .string "llamadas POKéMON!\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "Para algunos, los POKéMON son\n"
    .string "mascotas. Pero otros los usan\l"
    .string "para pelear.\p"
    .string "En cuanto a mí…\n"
    .string "Estudio POKéMON como profesión.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Bueno cuéntame algo de ti.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Pero primero dime cómo te llamas.\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Bien…\n"
    .string "¿Te llamas {PLAYER}?$"

gOakSpeech_Text_WhatWasHisName::
    .string "Este es mi nieto.\p"
    .string "Ha sido tu rival desde que ambos\n"
    .string "erais bebés.\p"
    .string "…Eh… ¿cómo se llamaba?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "¿Cómo era su nombre?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…¿Era {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "¡Eso es! ¡Ya me acuerdo!\n"
    .string "¡Se llamaba {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "¡{PLAYER}!\p"
    .string "¡Tu propia leyenda de POKéMON está\n"
    .string "a punto de comenzar!\p"
    .string "¡Te espera un mundo de sueños \n"
    .string "y aventuras con POKéMON! ¡Vamos!$"
