MtPyre_1F_Text_Healing_1::
    .string "Tus Pokémon parecen cansados,\n"
    .string "déjame que los cure.$"

MtPyre_1F_Text_Healing_2::
    .string "Parece que los espíritus están\n"
    .string "revolucionados. Ten cuidado.$"

MtPyre_1F_Text_BlockExteriorTrigger_1::
    .string "¡Alto ahí!$"

MtPyre_1F_Text_BlockExteriorTrigger_2::
    .string "No puedo dejarte pasar todavía.\n"
    .string "Una extraña fuerza me obliga a\l"
    .string "retenerte.$"

MtPyre_1F_Text_UnblockExteriorTrigger_1::
    .string "Los espíritus te invitan a\n"
    .string "salir al exterior.\p"
    .string "Ve con mucha precaución.$"

MtPyre_1F_Text_HikerEnd::
    .string "Gracias por traerme a la salida,\n"
    .string "espero que te vaya bien\p"
    .string "¡Nos vemos!$"