LavenderTown_Text_DoYouBelieveInGhosts::
    .string "¿Crees en los fantasmas?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "¡Por supuesto que sí!\n"
    .string "Que nos lo digan a nosotros…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "¿En serio?\p"
    .string "¿No ves a tu alrededor?\n"
    .string "Pero si está lleno de fantasmas…$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Parece que el hechizo protector\n"
    .string "no ha funcionado.\p"
    .string "Supongo que tendremos que\n"
    .string "prepararnos para lo peor.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Los espíritus han tomado el pueblo.\p"
    .string "Parecen proceder de la TORRE\n"
    .string "POKéMON pero, ¿qué quieren?$"

LavenderTown_Text_TownSign::
    .string "PUEBLO LAVANDA {STR_VAR_1}\n"
    .string "El noble pueblo púrpura.$"

LavenderTown_Text_SilphScopeNotice::
    .string "SILPH S.A.\p"
    .string "¡El nuevo SCOPE SILPH!\p"
    .string "¡Hace visible lo invisible!$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "CASA POKéMON DE VOLUNTARIOS\n"
    .string "DE PUEBLO LAVANDA$"

LavenderTown_Text_PokemonTowerSign::
    .string "TORRE POKéMON: que las almas de\n"
    .string "los POKéMON descansen en paz.$"

LavenderTown_Text_TriggerEscape::
    .string "¡Una fuerza paranormal arrastró a\n"
    .string "{PLAYER} hacia atrás!$"

LavenderTown_Text_TriggerEscape1::
    .string "De repente a {PLAYER} le ha entrado\n"
    .string "mucho sueño…$"

LavenderTown_Text_TriggerEscapeBlackout::
    .string "{PLAYER} ha perdido el conocimiento…$"

LavenderTown_Text_MisticoIntroduccion::
    .string "Saludos, {PLAYER}.\n"
    .string "Como ya habrás podido observar,\l"
    .string "aquí en Pueblo Lavanda se\l"
    .string "respira un ambiente enrarecido.\p"
    .string "Están sucediendo cosas extrañas.\n"
    .string "Dejaré que lo explores a tu\l"
    .string "ritmo mientras te preparas.\p"
    .string "Habla con los habitantes y\n"
    .string "empápate de conocimiento\l"
    .string "popular.\p"
    .string "Yo te estaré vigilando aquí hasta\n"
    .string "que te hayas puesto al día.$"

LavenderTown_Text_BloqueoCasaFuji::
    .string "Lo siento, no puedo dejarte entrar.\n"
    .string "Están conjurando un hechizo\l"
    .string "protector en el interior.$"

LavenderTown_Text_Mistico_1::
    .string "Buenas, {PLAYER}.\p"
    .string "Veo que aún no has escuchado al\n"
    .string "Pueblo, por lo que no puedo\l"
    .string "dejarte entrar a la Torre aún.$"

LavenderTown_Text_Mistico_2::
    .string "{PLAYER}, ahora conoces las\n"
    .string "historias del Pueblo.\p"
    .string "La sabiduría te ha sido\n"
    .string "transferida y has conseguido\l"
    .string "buenos aliados.\p"
    .string "Adelante, la misión te espera.$"