LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "TEAM ROCKET will do anything for\n"
    .string "the sake of money!\p"
    .string "There is no job too dirty, no deed\n"
    .string "too heinous, no crime too wicked!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "Permíteme que te devuelva\n"
    .string "a tu camino.\p"
    .string "1…{PAUSE 10} 2…{PAUSE 10} y…{PAUSE 20} 3…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "You know how the CUBONE species\n"
    .string "wears skulls, right?\p"
    .string "People will pay a lot for one.$"

