PokemonTower_6F_Text_AngelicaIntro::
    .string "Dame…\n"
    .string "sangre…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "¡Aah!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "Tengo hambre…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urff…\n"
    .string "¡Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "¡Algo está fallando!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "¡No ha sido mi culpa!\n"
    .string "¡Era un espíritu!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "¡Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "¡Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "¿Qué está pasando aquí?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Be gone…\n"
    .string "Intruders…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "The ghost was the restless spirit\n"
    .string "of CUBONE's mother!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "The mother's spirit was calmed.\p"
    .string "It departed to the afterlife…$"

