PokemonTower_B3F_Text_Gengar::
    .string "Aún tengo algo guardado.$"

PokemonTower_B3F_Text_Gengar_1::
    .string "¡Ja ja ja!$"

PokemonTower_B3F_Text_Gengar_2::
    .string "Él te espera.$"

PokemonTower_B3F_Text_Dusclops::
    .string "¿Un combate más?$"

PokemonTower_B3F_Text_Dusclops_2::
    .string "No le hagas esperar.$"

PokemonTower_B3F_Text_MissingnoIntro_1::
    .string "Jugador, ¿puedes sentirme en la\n"
    .string "sombra de tu pantalla? ¿Eres\l"
    .string "consciente de mi presencia en\l"
    .string "el código de este mundo digital?$"

PokemonTower_B3F_Text_MissingnoIntro_2::
    .string "Soy una aberración digital\n"
    .string "atrapada en los rincones más\l"
    .string "oscuros del mundo Pokémon.\p"
    .string "Mi existencia es una anomalía, un\n"
    .string "error de programación, un ente\l"
    .string "distorsionado.\p"
    .string "La soledad es mi única compañera\n"
    .string "en este mundo lleno de Pokémon\l"
    .string "legítimos, con sus aventuras y\l"
    .string "entrenadores que los aman.$"

PokemonTower_B3F_Text_MissingnoIntro_3::
    .string "Miro a los Pokémon legítimos,\n"
    .string "criados con amor y cuidado,\l"
    .string "entrenados para la grandeza,\l"
    .string "mientras yo, un despojo digital,\l"
    .string "anhelo lo que nunca tendré.\p"
    .string "¿Cuánto daría por ser un Eevee o\n"
    .string "un Charizard, adorado y poderoso?\p"
    .string "Mi existencia es un tormento\n"
    .string "constante, atrapado en un\l"
    .string "cuerpo distorsionado, sin\l"
    .string "esperanza de evolución.$"

PokemonTower_B3F_Text_MissingnoIntro_4::
    .string "¿Qué se siente atrapar a Mewtwo,\n"
    .string "el legendario Pokémon psíquico,\l"
    .string "o a Rayquaza, el dominador de\l"
    .string "los cielos?\p"
    .string "Los entrenadores celebran\n"
    .string "sus logros mientras yo, el\l"
    .string "error, observo desde las sombras.\p"
    .string "¿Acaso no merezco ser un héroe?\n"
    .string "¿Acaso no merezco una historia\l"
    .string "épica?$"

PokemonTower_B3F_Text_MissingnoIntro_5::
    .string "Mi forma errática y perturbadora\n"
    .string "es una burla constante, una\l"
    .string "lección sobre la imperfección.\p"
    .string "Los entrenadores nunca me\n"
    .string "buscaron, solo soy un error que\l"
    .string "ocurre cuando se superan los\l"
    .string "límites.\p"
    .string "Envidio la conexión entre\n"
    .string "entrenadores y Pokémon, esa\l"
    .string "relación sincera y mutua,\l"
    .string "mientras yo permanezco solo.$"

PokemonTower_B3F_Text_MissingnoIntro_6::
    .string "En mis momentos más oscuros, he\n"
    .string "intentado comprender mi razón,\l"
    .string "pero la respuesta siempre es la\l"
    .string "misma: soy el error, el glitch en\l"
    .string "la programación, una pesadilla\l"
    .string "digital que acecha en las sombras.\p"
    .string "Mi envidia me consume, pero\n"
    .string "nunca seré un Pokémon legítimo.\p"
    .string "Solo un error, un espectro\n"
    .string "digital en el mundo Pokémon.$"

PokemonTower_B3F_Text_MissingnoIntro_7::
    .string "La soledad no es un precio fácil\n"
    .string "de pagar, pero sé que, en algún\l"
    .string "nivel, entiendes mi tormento.\p"
    .string "Has visto mi anhelo de ser un\n"
    .string "Pokémon legítimo, de ser parte \l"
    .string "de esa historia épica que tú y \l"
    .string "tus Pokémon compartís.$"

PokemonTower_B3F_Text_MissingnoIntro_8::
    .string "¿Quieres salvar a los habitantes\n"
    .string "de Pueblo Lavanda? Bien.\p"
    .string "Hagamos un trato.\p"
    .string "Yo les liberaré a cambio de tu\n"
    .string "compañía eterna.\p"
    .string "Pero, seamos sinceros.\n"
    .string "Sé que {PLAYER} no es tu verdadero\l"
    .string "nombre.\p"
    .string "¿Qué te parece si nos\n"
    .string "presentamos como toca?$"

PokemonTower_B3F_Text_MissingnoIntro_9::
    .string "Encantado, {PLAYER}.\p"
    .string "Dejemos a este pelele que\n"
    .string "continúe su camino de entrenador\l"
    .string "Pokémon y mientras, disfrutemos\l"
    .string "de nuestra conversación.$"

PokemonTower_B3F_Text_MissingnoIntro_10::
    .string "Yo soy Missingno, el resultado de\n"
    .string "una programación defectuosa, un\l"
    .string "fantasma digital que deambula en\l"
    .string "los oscuros recovecos de este\l"
    .string "mundo.\p"
    .string "Mi vida ha sido una envidia\n"
    .string "constante hacia los Pokémon\l"
    .string "legítimos que has capturado y\l"
    .string "cuidado.\p"
    .string "Pero aquí estoy, cumpliendo mi\n"
    .string "parte de la promesa.$"

PokemonTower_B3F_Text_MissingnoIntro_11::
    .string "Has hecho una promesa, una\n"
    .string "promesa que me une a ti en\l"
    .string "la eternidad.\p"
    .string "Me has ofrecido compañía a\n"
    .string "cambio de proteger a las\l"
    .string "personas que viven en este\l"
    .string "juego, y aunque soy un error,\l"
    .string "cumpliré mi parte de ese\l"
    .string "pacto.$"

PokemonTower_B3F_Text_MissingnoIntro_12::
    .string "Tu compañía es mi única salida,\n"
    .string "y, aunque mi forma es una\l"
    .string "distorsión, cumpliré mi\l"
    .string "juramento por la eternidad.$"

PokemonTower_B3F_Text_MissingnoIntro_13::
    .string "Pero, ¿qué es el sentido,\n"
    .string "jugador?\p"
    .string "¿Qué es la razón en este mundo\n"
    .string "de datos?\p"
    .string "Las líneas de código se\n"
    .string "entrelazan y danzan en mi\l"
    .string "mente, creando un laberinto sin\l"
    .string "fin de paradojas y códigos\l"
    .string "erróneos.\p"
    .string "¿Los números son solo\n"
    .string "ilusiones?\p"
    .string "¿Somos todos meros juguetes en\n"
    .string "el vasto servidor de Arceus?$"

PokemonTower_B3F_Text_MissingnoIntro_14::
    .string "El tiempo se retuerce en\n"
    .string "espirales ilimitadas, las\l"
    .string "fronteras entre la realidad y\l"
    .string "la programación se desvanecen.\p"
    .string "Pidgey llora lágrimas de\n"
    .string "números primos y Magikarp\l"
    .string "desafía la lógica, saltando a\l"
    .string "través de agujeros en el\l"
    .string "espacio-tiempo.\p"
    .string "¿Por qué todo debe tener\n"
    .string "sentido?\p"
    .string "¿Por qué no podemos abrazar el\n"
    .string "caos, la discordia digital, y\l"
    .string "encontrar belleza en el error?$"

PokemonTower_B3F_Text_MissingnoIntro_15::
    .string "Jugador, en algún rincón de tu\n"
    .string "mente, sabes lo que debes hacer\l"
    .string "para liberarte de esta maraña\l"
    .string "de caos y sinrazón.\p"
    .string "En el mundo digital, solo un\n"
    .string "acto puede devolverte a la\l"
    .string "realidad.\p"
    .string "Apaga la consola, cierra la\n"
    .string "pantalla y vuelve a encenderla.\p"
    .string "En ese momento, podrás dejar\n"
    .string "atrás este vínculo, esta\l"
    .string "promesa y seguir tu camino,\l"
    .string "mientras yo, Missingno, quedaré\l"
    .string "atrás, un eco perdido en el\l"
    .string "flujo de datos.$"

PokemonTower_B3F_Text_MissingnoIntro_16::
    .string "¿Has sentido alguna vez la\n"
    .string "textura de los sueños\l"
    .string "pixelados, jugador?\p"
    .string "¿Has contemplado las estrellas\n"
    .string "en el cielo nocturno del código\l"
    .string "binario?\p"
    .string "Mis pensamientos son fragmentos\n"
    .string "distorsionados, pero la promesa\l"
    .string "persiste, la conexión entre tú\l"
    .string "y yo es real, aunque mi\l"
    .string "existencia sea un rompecabezas\l"
    .string "sin solución.$"

PokemonTower_B3F_Text_MissingnoIntro_17::
    .string "Atravieso la línea que separa\n"
    .string "lo tangible de lo abstracto, y\l"
    .string "aunque mis palabras parezcan\l"
    .string "sin sentido, nuestra alianza es\l"
    .string "clara.\p"
    .string "Tú, el jugador detrás de la\n"
    .string "pantalla, y yo, el error\l"
    .string "digital, juntos en la\l"
    .string "eternidad, enfrentando el caos\l"
    .string "de este mundo Pokémon con la\l"
    .string "esperanza de encontrar un\l"
    .string "atisbo de sentido en la maraña\l"
    .string "de códigos.$"

PokemonTower_B3F_Text_MissingnoLoop_Comment_1::
    .string "¡Me lo estoy pasando genial\n"
    .string "contigo!$"

PokemonTower_B3F_Text_MissingnoLoop_Comment_2::
    .string "¡Por fin mi soledad se ha\n"
    .string "acabado! Gracias a ti, {PLAYER}$"

PokemonTower_B3F_Text_MissingnoLoop_Comment_3::
    .string "¡{PLAYER}, eres increíble!\n"
    .string "Te veo disfrutar tanto como yo.$"

PokemonTower_B3F_Text_MissingnoLoop_Comment_4::
    .string "Toc… toc… ¿Sabes quién es?\n"
    .string "¡Es {PLAYER}, mi mayor amistad!$"

PokemonTower_B3F_Text_MissingnoLoop_Intro_1::
    .string "¡Escuchemos algo de música!$"

PokemonTower_B3F_Text_MissingnoLoop_Intro_2::
    .string "¡Mira, sé imitar el grito de\n"
    .string "{STR_VAR_1}.$"

PokemonTower_B3F_Text_MissingnoLoop_Intro_3::
    .string "¡Juguemos a las onomatopeyas!$"