MtPyre_Summit_Text_Trigger_Dusclops_1::
    .string "Vete…{PAUSE_UNTIL_PRESS} o te llevaré\n"
    .string "conmigo.$"

MtPyre_Summit_Text_Trigger_Dusclops_2::
    .string "Tú…{PAUSE_UNTIL_PRESS} lo…{PAUSE_UNTIL_PRESS} has…{PAUSE_UNTIL_PRESS}\n"
    .string "…{PAUSE_UNTIL_PRESS} querido…$"

MtPyre_Summit_Text_Trigger_Dusclops_3::
    .string "Crees que puedes ganar…{PAUSE_UNTIL_PRESS}\n"
    .string "no tienes ni idea…$"

MtPyre_Summit_Text_Trigger_Hiker_1::
    .string "¿Qué ha pasado?\n"
    .string "¿Cómo hemos llegado hasta aquí?\p"
    .string "¿Me has salvado del fantasma?\n"
    .string "¡Muchísimas gracias!\p"
    .string "Vayamos a la salida.$"

MtPyre_Summit_Text_Trigger_Dusclops_Defeated::
    .string "¿Qué? ¿Dónde estoy?$"