LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
LavenderTown_House1_Text_HistoriaMrMime_1::
    .string "¿Qué está pasando?\n"
    .string "Tengo mucho miedo…\p"
    .string "¡Ya lo sé!\p"
    .string "Cuando tenía miedo de niña\n"
    .string "mi abuela me contaba historias.\p"
    .string "¿Quieres que te cuente una?$"

LavenderTown_House1_Text_HistoriaMrMime_2::
    .string "“Una familia en Ciudad Carmín\n"
    .string "vivía aterrada por los espíritus.”\p"
    .string "“Los espíritus ponían toda su casa\n"
    .string "patas arriba noche tras noche”\p"
    .string "“Un día apareció un Mr. Mime creó\n"
    .string "una barrera rodeando la casa\l"
    .string "y se enfrentó a los espíritus.”\p"
    .string "“¡Hubo un estallido de luz\n"
    .string "y un chillido agudo!”\p"
    .string "“Cuando se desvaneció la luz,\n"
    .string "el espíritu malévolo desapareció\l"
    .string "y la paz regresó a la casa.”\p"
    .string "“Mr. Mime salvó a la familia\n"
    .string "y se convirtió en su guardián,\l"
    .string "manteniendo la oscuridad a raya\l"
    .string "para siempre.”$"

LavenderTown_House1_Text_HistoriaMrMime_3::
    .string "Uf, ojalá tener un Mr. Mime\n"
    .string "cerca…$"

LavenderTown_House1_Text_HistoriaMrMime_4::
    .string "¿Qué ha sido eso?$"

LavenderTown_House1_Text_HistoriaMrMime_5::
    .string "Es… píritus… a… quí…$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "The ghost of POKéMON TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"

