VermilionCity_Text_GrimerMultipliesInSludge::
VermilionCity_Text_WomanBattle::
    .string "Devoraré… tu esencia…$"

VermilionCity_Text_WomanBattle2::
    .string "Me… desvanezco…$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
VermilionCity_Text_BattleOldMan::
    .string "Huelo… energía vital…\n"
    .string "Dame…$"

VermilionCity_Text_BattleOldManWin::
    .string "Me… lleva…\n"
    .string "Ayuda…$"

VermilionCity_Text_BattleAfter::
    .string "…$"

VermilionCity_Text_DungeonUnblocked::
    .string "Parece que las barreras\n"
    .string "de la casa del tejado azul\l"
    .string "han desaparecido…$"

VermilionCity_Text_SSAnneHasDepartedForYear::
VermilionCity_Text_SailorBattle::
    .string "Únete… a…\n"
    .string "nosotros…$"

VermilionCity_Text_SailorBattle2::
    .string "Ah… ah…\n"
    .string "Aaaaah…$"

VermilionCity_Text_BuildingOnThisLand::
VermilionCity_Text_BattleOldMan2::
    .string "Me quedaré…\n"
    .string "con… TU ALMA…$"

VermilionCity_Text_BattleOldMan2Win::
    .string "¿Qué…\n"
    .string "pasa…?$"

VermilionCity_Text_Machop::
    .string "¿Mime?$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "Mr. Mime usó Teletransporte.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "The S.S. ANNE is a famous luxury\n"
    .string "cruise ship.\p"
    .string "It visits VERMILION once a year.$"

VermilionCity_Text_CitySign::
    .string "CIUDAD CARMÍN\n"
    .string "El puerto de los ocasos exquisitos.$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "NOTICE!\p"
    .string "ROUTE 12 may be blocked off by a\n"
    .string "sleeping POKéMON.\p"
    .string "Detour through ROCK TUNNEL to\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLICE$"

VermilionCity_Text_PokemonFanClubSign::
    .string "CLUB DE FANS DE POKéMON\n"
    .string "¡Bienvenidos todos!$"

VermilionCity_Text_GymSign::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\l"
    .string "¡El Rayo americano!$"

VermilionCity_Text_VermilionHarbor::
    .string "PUERTO CARMÍN$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "Welcome to the S.S. ANNE!\p"
    .string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}Great!\n"
    .string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}Sorry!\p"
    .string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail::
    .string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, you have a TRI-PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Okay, everything's in order.\p"
    .string "SEAGALLOP HI-SPEED 7 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, you have a RAINBOW PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Oh! That's a MYSTICTICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "NAVEL ROCK anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Oh! That's an AURORATICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "BIRTH ISLAND anytime.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 10 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 12 will be\n"
    .string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of PROF. OAK's AIDES.\p"
    .string "Did you meet the other AIDE?\p"
    .string "He had a package from PROF. OAK\n"
    .string "for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "ROUTE 2, {PLAYER}.\p"
    .string "If you're in the ROUTE 2 area,\n"
    .string "please look for him.$"

