PokemonTower_B1F_Text_Trigger::
    .string "A {PLAYER} le está entrando sueño…$"

PokemonTower_B1F_Text_Trigger_2::
    .string "{PLAYER} se ha dormido…$"

PokemonTower_B1F_Text_TipLady_Intro::
    .string "Hola, {PLAYER}…\p"
    .string "He conseguido establecer una\n"
    .string "conexión psíquica contigo.\p"
    .string "Veo que tienes complicaciones\n"
    .string "para continuar…$"

PokemonTower_B1F_Text_TipLady_NeedTip::
    .string "Puedo conseguirte ayuda, mas no\n"
    .string "será gratis.\p"
    .string "Debo llevarme el alma de uno de\n"
    .string "tus Pokémon.$"

PokemonTower_B1F_Text_TipLady_DoYouAgree::
    .string "¿Estás de acuerdo?$"

PokemonTower_B1F_Text_TipLady_WhichPokemon::
    .string "¿Qué Pokémon me entregas?$"

PokemonTower_B1F_Text_TipLady_Ending::
    .string "Estaré aquí por si necesitas\n"
    .string "ayuda.$"

PokemonTower_B1F_Text_TipLady_NoMoreTips::
    .string "Lo lamento, no puedo ofrecerte\n"
    .string "más ayuda.$"

PokemonTower_B1F_Text_TipLady_OnlyOneAliveMonInParty::
    .string "No puedo llevarme tu último\n"
    .string "Pokémon."

PokemonTower_B1F_Text_TipLady_TakePokemon::
	.string "No te preocupes, {STR_VAR_1} no sufrirá.$"

PokemonTower_B1F_Text_TipLady_TakePokemon_2::
	.string "Despídete de {STR_VAR_1}…$"

PokemonTower_B1F_Text_TipLady_NeedMore::
    .string "¿Necesitas más ayuda?$"