
VermilionCity_Dungeon2_Text_Father::
    .string "Por favor, no nos hagas daño…\n"
    .string "¡Haremos lo que sea!$"

VermilionCity_Dungeon2_Text_Evil1::
    .string "Quiero… almas…$"

VermilionCity_Dungeon2_Text_Mother::
    .string "¡No! ¡Llévanos a nosotros!\n"
    .string "¡Pero deja a nuestro hijo libre!$"

VermilionCity_Dungeon2_Text_Evil2::
    .string "Quiero… tres… almas…$"

VermilionCity_Dungeon2_Text_Evil3::
    .string "Huelo… ¿cuatro?… almas…$"

VermilionCity_Dungeon2_Text_Evil4::
    .string "Día suerte… cinco… almas…$"

VermilionCity_Dungeon2_Text_Evil5::
    .string "¿Luchar…?\nEso es risa…$"

VermilionCity_Dungeon2_Text_Evil6::
    .string "Esto… no acabado…$"

VermilionCity_Dungeon2_Text_MrMime::
    .string "¡Mime!$"

VermilionCity_Dungeon2_Text_Father2::
    .string "¡Muchas gracias por salvarnos!\n"
    .string "¿Cómo podría agradece…$"

VermilionCity_Dungeon2_Text_Father3::
    .string "¿Qué ha sido eso?$"