PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: ¡Hola, {PLAYER}!\n"
    .string "Veo que te las has apañado para\l"
    .string "llegar hasta aquí.\p"
    .string "¡Están pasando cosas muy raras!\p"
    .string "¡Déjame comprobar que eres\n"
    .string "suficientemente fuerte!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "¿Y ya está?\n"
    .string "¿Eso es todo?\p"
    .string "¡Te he dado ventaja!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "Mira, acabo de rescatar un\n"
    .string "Cubone.\p"
    .string "No he podido localizar a su madre,\n"
    .string "pero confío en que tú sí.\p"
    .string "Voy a dejar que te acompañe, pero\n"
    .string "no dejes que le pase nada.$"

PokemonTower_2F_Text_RivalPostBattle_2::
    .string "¡Me piro, vampiro!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Estos fantasmas no se dejan\n"
    .string "reconocer.\p"
    .string "El SILPH SCOPE debería permitir\n"
    .string "identificarlos.$"

PokemonTower_2F_Text_ObtainedACubone::
    .string "¡{PLAYER} recibió a Cubone!$"