PokemonTower_3F_Text_HopeIntro::
    .string "Urrg… Awaa…\n"
    .string "Huhu… Graa…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "¡Mwa!\n"
    .string "¡Me he liberado!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "No sé qué está sucediendo,\n"
    .string "pero te he percibido en visiones.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "¡Kekeke…\n"
    .string "¡Kwaaah!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "¿Mmm?\n"
    .string "¿Qué estaba haciendo?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "¡Lo siento!\n"
    .string "¡Estaba fuera de mí!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "¡Largo!\n"
    .string "¡Espíritus malvados!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "¡Buf!\n"
    .string "¡El espíritu se fue!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "Los demás…\n"
    .string "¿Habrán sido poseidos también?$"

