PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: El abuelo se fue\n"
    .string "a capturar Pokémon.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: ¡Abuelo!\n"
    .string "¡Estoy harto de esperar!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: ¡No es justo!\n"
    .string "¿Y yo qué?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: ¡No seas tan tiquismiquis!\n"
    .string "¡Elige ya, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: ¡Entonces me quedo con este!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} recibió el {STR_VAR_1}\n"
    .string "del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Mi POKéMON parece\n"
    .string "más fuerte que el tuyo.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: ¡Espera, {PLAYER}!\n"
    .string "¡Veamos quién es más fuerte!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "¿Qué?\n"
    .string "¡No puede ser!\l"
    .string "¡Elegí el Pokémon equivocado!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: ¡Sí!\n"
    .string "¡Soy genial!$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: ¡Bien!\n"
    .string "¡Entrenaré para ser mejor que tú!\p"
    .string "{PLAYER}, Abuelo,\n"
    .string "¡Nos vemos!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: ¡Abuelo!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: I almost forgot!\n"
    .string "What did you call me for?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: All right, Gramps!\n"
    .string "Leave it all to me!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, I hate to say it, but you\n"
    .string "won't be necessary for this.\p"
    .string "I know! I'll borrow a TOWN MAP\n"
    .string "from my sis!\p"
    .string "I'll tell her not to lend you one,\n"
    .string "{PLAYER}! Hahaha!\p"
    .string "Don't bother coming around to\n"
    .string "my place after this!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: ¿{RIVAL}?\n"
    .string "Déjame pensar…\p"
    .string "Oh, sí, te pedí que\n"
    .string "vinieras. Espera…\p"
    .string "Toma, {PLAYER}.\p"
    .string "Aquí hay tres POKéMON.\p"
    .string "Los POKéMON están dentro de\n"
    .string "estas POKé BALLS.\p"
    .string "De joven, fui un gran\n"
    .string "entrenador de POKéMON.\p"
    .string "Pero ahora, en mi vejez, solo me\n"
    .string "quedan estos tres.\p"
    .string "Puedes elegir uno.\n"
    .string "¡Adelante, elige!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: Tranquilo, {RIVAL}.\n"
    .string "Tú tendrás otro!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: Ahora, {PLAYER}.\p"
    .string "Dentro de esas tres POKé BALLS hay\n"
    .string "POKéMON.\p"
    .string "¿Cuál elegirás para ti?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: ¡Hey!\n"
    .string "¡No te vayas aún!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "Bien, {PLAYER}, ¿Entonces eliges\n"
    .string "a CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "Bien, {PLAYER}, ¿Entonces eliges\n"
    .string "a SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "Bien, {PLAYER}, ¿Entonces eliges\n"
    .string "a BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "¡Buena elección!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "¡{PLAYER} recibió el {STR_VAR_1}\n"
    .string "de manos del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: ¡Si aparece un POKéMON\n"
    .string "salvaje, tu POKéMON podrá luchar\l"
    .string "contra él!\p"
    .string "Junto a él, no te será difícil\n"
    .string "llegar a la siguiente ciudad.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: ¡{STRING 01}, entrena a tu joven\n"
    .string "POKéMON luchando!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: Oh, {PLAYER}!\n"
    .string "How is my old POKéMON?\p"
    .string "Well, it seems to be growing more\n"
    .string "attached to you.\p"
    .string "You must be talented as a POKéMON\n"
    .string "TRAINER.\p"
    .string "What's that?\n"
    .string "You have something for me?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} delivered OAK'S PARCEL.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "Ah! \n"
    .string "It's the custom POKé BALL!\p"
    .string "I had it on order.\n"
    .string "Thank you!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: Oh, right!\n"
    .string "I have a request for you two.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "On the desk there is my invention,\n"
    .string "the POKéDEX!\p"
    .string "It automatically records data on\n"
    .string "POKéMON you've seen or caught.\p"
    .string "It's a high-tech encyclopedia!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} and {RIVAL}.\n"
    .string "Take these with you.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} received the POKéDEX\n"
    .string "from PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: You can't get detailed data\n"
    .string "on POKéMON by just seeing them.\p"
    .string "You must catch them to obtain\n"
    .string "complete data.\p"
    .string "So, here are some tools for\n"
    .string "catching wild POKéMON.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} received five POKé BALLS.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "When a wild POKéMON appears,\n"
    .string "it's fair game.\p"
    .string "Just throw a POKé BALL at it and\n"
    .string "try to catch it!\p"
    .string "This won't always work, however.\p"
    .string "A healthy POKéMON can escape.\n"
    .string "You have to be lucky!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "To make a complete guide on all\n"
    .string "the POKéMON in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old.\n"
    .string "I can't get the job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "POKéMON around the world wait for\n"
    .string "you, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Those are POKé BALLS.\n"
    .string "They contain POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "That's PROF. OAK's last POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "Press START to open the MENU!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "The SAVE option is on the MENU.\n"
    .string "Use it regularly.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "All POKéMON types have strong and\n"
    .string "weak points against others.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "¡Hay un correo electrónico!\p"
    .string "…\p"
    .string "¡Aviso a todos los ENTRENADORES\n"
    .string "de POKéMON!\p"
    .string "¡Los ENTRENADORES de élite de la\n"
    .string "LIGA POKéMON están listos para\l"
    .string "desafiaros a todos!\p"
    .string "¡Traed a vuestros mejores POKéMON\n"
    .string "para ver lo buenos que sois!\p"
    .string "CG de la LIGA POKéMON, MESETA\n"
    .string "AÑIL\p"
    .string "PD: ¡PROF. OAK, visítenos por\n"
    .string "favor!…$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Estudio a los Pokémon, soy\n"
    .string "el ayudante del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "El PROF. OAK va a tener su\n"
    .string "propio programa de radio.\p"
    .string "Será el Seminario sobre Pokémon\n"
    .string "del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "¡El PROF. OAK es un experto\n"
    .string "en POKéMON!\p"
    .string "¡Es admirado por muchos de los\n"
    .string "ENTRENADORES POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more POKéMON,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK took both POKéDEX\n"
    .string "units.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'s POKéDEX was upgraded!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"

