MtPyre_6F_Text_InteriorEventTrigger_Hiker_1::
    .string "¡Oh! ¿Qué pasa pequeñín?\n"
    .string "¿Sabías que me había perdido y\l"
    .string "venías a buscarme?\p"
    .string "¡Qué suerte la mía!\n"
    .string "¡La leyenda era cierta!$"

MtPyre_6F_Text_InteriorEventTrigger_Hiker_2::
    .string "Hmmm… ¿Notas esa presencia?$"

MtPyre_6F_Text_InteriorEventTrigger_Hiker_3::
    .string "¡AAAAAAAAH!$"

MtPyre_6F_Text_InteriorEventTrigger_Dusclops::
    .string "Dame… ¡tu ser!$"

MtPyre_6F_Text_InteriorEventTrigger_Vulpix::
    .string "¡Piiiix!$"

MtPyre_6F_Text_InteriorEventTrigger_FollowVulpix::
    .string "Vulpix quiere que le sigas.$"