LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Están pasando cosas muy raras.\n"
    .string "¿Por qué el Sr. Fuji parece tan\l"
    .string "tranquilo?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "Los… espíritus…\n"
    .string "Se llevaron al Sr. Fuji…$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Aquí vive el Señor Fuji.\p"
    .string "Es la persona más sabia del pueblo.\p"
    .string "Conoce un montón de historias\n"
    .string "sobre Pokémon.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "¡Tengo miedo!\n"
    .string "¿Los Pokémon suelen ser tan malos?$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug2::
    .string "¿Dónde está el Sr. Fuji?$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your POKéDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for POKéMON,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Try using it on POKéMON that are\n"
    .string "sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "Es un…{PAUSE_UNTIL_PRESS} ¿Un hechizo de protección\n"
    .string "contra los malos espíritus?$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "Un montón de libros antiguos.$"

LavenderTown_VolunteerPokemonHouse_Text_HistoriaVulpix1::
    .string "Todo esto que está sucediendo en\n"
    .string "Pueblo Lavanda me recuerda\l"
    .string "a una historia que dice así:$"

LavenderTown_VolunteerPokemonHouse_Text_HistoriaVulpix2::
    .string "“En la lúgubre noche del\n"
    .string "Monte Pírico, un solitario viajero\l"
    .string "se adentró en el espeso bosque.”\p"
    .string "“Un espíritu vengativo acechaba,\n"
    .string "susurros oscuros llenaban el aire.”\p"
    .string "“En ese momento de desesperación,\n"
    .string "un Vulpix de nueve colas apareció.”\p"
    .string "Su pelaje brillaba en la.\n"
    .string "oscuridad.”\p"
    .string "“Vulpix guió al viajero por\n"
    .string "los caminos esquivos, alejándolo\l"
    .string "del espíritu.”\p"
    .string "“Finalmente, al amanecer, el\n"
    .string "espíritu cedió y Vulpix desapareció\l"
    .string "en la luz del día como un guardián\l"
    .string "místico.”$"

LavenderTown_VolunteerPokemonHouse_Text_HistoriaVulpix3::
    .string "¡Ah! ¿Qué está pasando?$"