Text_UltimateMoveThatMon::
    .string "He perfeccionado el último\n"
    .string "movimiento de este tipo…\p"
    .string "Bueno, y ahora, ¿a quién se lo\n"
    .string "enseño?\p"
    .string "Mmmm…\p"
    .string "Ese {STR_VAR_1} tuyo…$"

Text_JustMistaken::
    .string "No, no…\n"
    .string "Me he equivocado.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "¡Anda, éste es!\n"
    .string "¡Éste es el POKéMON!\p"
    .string "¡Este {STR_VAR_1} se merece\n"
    .string "aprender mi último movimiento!\p"
    .string "¿Te parece bien?\p"
    .string "¿Quieres que le enseñe {STR_VAR_1}\n"
    .string "mi {STR_VAR_2} a tu {STR_VAR_1}?$"

Text_YouRejectIt::
    .string "¿Cómo, que no?\n"
    .string "¡No me lo puedo creer!$"

Text_LetMeConferUltimateMove::
    .string "¿Quieres?\p"
    .string "Pues voy a enseñarle\n"
    .string "mi {STR_VAR_2} a tu {STR_VAR_1}.\p"
    .string "¡Allá voy!$"

Text_TaughtMove::
    .string "Qué emoción…\p"
    .string "No pensé que llegara a enseñar\n"
    .string "al final el movimiento…$"

Text_MakeBestUseOfMove::
    .string "¡Espero que lo uses bien y\n"
    .string "le saques el mayor partido!$"

Text_PassedOnEverythingIKnow::
    .string "Qué emoción…\p"
    .string "Qué tranquilidad.\n"
    .string "Ya he transmitido todo lo que sé.\p"
    .string "Qué satisfacción cumplir con el\n"
    .string "deber.$"

Text_FeelRejuvenated::
    .string "Ahora que sabes lo que yo, siento\n"
    .string "una tranquilidad enorme.\p"
    .string "¡Me siento hasta más joven!\n"
    .string "¡Es como si me hubiera quitado\n"
    .string "años de encima!$"
