PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "¡Ven, jóven!\n"
    .string "Esta zona está protegida.\l"
    .string "Puedes descansar aquí.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Dame… tu…\n"
    .string "existencia…$"

PokemonTower_5F_Text_TammyDefeat::
    .string "¡Fiuu!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "Me habían poseído.$"

PokemonTower_5F_Text_RuthIntro::
    .string "Te… está…\n"
    .string "esperando…$"

PokemonTower_5F_Text_RuthDefeat::
    .string "¡Qué pesadilla!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "Algo hablaba y actuaba por mí.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "¡Espíritus!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "¿Ah?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "He vuelto en mí.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Urgah…\n"
    .string "Urff…$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "¡Uuuh!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Caí en manos de espíritus malignos\n"
    .string " a pesar de mi entrenamiento…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "{PLAYER} entró en la zona protegida,\n"
    .string "el conjuro está funcionando.\p"
    .string "El equipo de {PLAYER} se ha\n"
    .string "recuperado.$"

