RuinsOfAlph_MainChamber_Text_Fisherman_1::
    .string "¿Dó… dónde estoy?$"

RuinsOfAlph_MainChamber_Text_Fisherman_2::
    .string "Me siento liberado. ¡Muchas gracias!$"

RuinsOfAlph_MainChamber_Text_Lady_1::
    .string "¿Por qué no me puedo mover?$"

RuinsOfAlph_MainChamber_Text_Lady_2::
    .string "¿Me has salvado tú?$"

RuinsOfAlph_MainChamber_Text_MrFuji_1::
    .string "¡Ah! ¡{PLAYER}, eres tú!\n"
    .string "De repente aparecí aquí, rodeado de\n"
    .string "fantasmas.\p"
    .string "No estoy a favor de la violencia, pero\n"
    .string "por favor, sácame de aquí.$"

RuinsOfAlph_MainChamber_Text_MrFuji_2::
    .string "¡Genial! ¡Parece que tenemos vía\n"
    .string "libre!\p"
    .string "¡Salgamos fuera de este lugar!$"

RuinsOfAlph_MainChamber_Text_Entei_1::
    .string "¡Grrrroooaaaah!$"

RuinsOfAlph_MainChamber_Text_Entei_2::
    .string "¡…!$"

RuinsOfAlph_MainChamber_Text_Entei_3::
    .string "Mis disculpas…\p"
    .string "No sé qué me ha pasado.\n"
    .string "No me gusta atacar a los humanos.\p"
    .string "Puedo ver que tu corazón es\nsincero.\p"
    .string "Además, tienes una misión,\n¿no es así?\p"
    .string "Te acompañaré en tu empeño,\n"
    .string "permíteme que te compense así.$"

RuinsOfAlph_MainChamber_Text_Entei_4::
    .string "Y ahora… {PAUSE 2}¡Volvamos\n"
    .string "al lugar de donde procedes!$"

RuinsOfAlph_MainChamber_Text_Blocking::
    .string "Algo está bloqueando el\n"
    .string "camino…$"