PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MOM: En fin…\n"
    .string "Todos los hijos se van de\l"
    .string "casa algún día.\p"
    .string "Por cierto, el PROF. OAK\n"
    .string "te buscaba.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MOM: En fin…\n"
    .string "Todas las hijas se van de\l"
    .string "casa algún día.\p"
    .string "Por cierto, el PROF. OAK\n"
    .string "te buscaba.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Solo se ven interferencias…\n"
    .string "Qué extraño….$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Solo se ven interferencias…\n"
    .string "Qué extraño….$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

