LavenderTown_House2_Text_Inspector_1::
    .string "En los años que llevo aquí, jamás\n"
    .string "había visto algo tan tenebroso.\p"
    .string "Yo vengo de Ciudad Trigal, en\n"
    .string "la región de Johto.\p"
    .string "En el Encinar hay muchas leyendas.\n"
    .string "¿Quieres que te las cuente?$"

LavenderTown_House2_Text_Inspector_2::
    .string "La primera dice así:$"

LavenderTown_House2_Text_Inspector_Historia_Farfetchd::
    .string "“En medio del encinar sombrío, un\n"
    .string "Farfetch’d salvaje se encontraba\l"
    .string "perdido y aterrado.”\p"
    .string "“La densa niebla ocultaba figuras\n"
    .string "espeluznantes de fantasmas que lo\l"
    .string "rodeaban.”\p"
    .string "“Cada noche, los lamentos y susurros\n"
    .string "retumbaban en sus oídos.”\p"
    .string "“Un joven entrenador, con valentía,\n"
    .string "se adentró en el encinar en busca\l"
    .string "de su primer Pokémon.”\p"
    .string "“Cuando encontró al atemorizado\n"
    .string "Farfetch’d, lo nombró ’Valiente’.”\p"
    .string "“Al escuchar su nuevo nombre, el\n"
    .string "Pokémon recuperó la confianza y se\l"
    .string "armó con su puerro, enfrentando a\l"
    .string "los espíritus con decisión.”\p"
    .string "“La fuerza del vínculo entre el\n"
    .string "entrenador y Valiente disipó a los\l"
    .string "espíritus maliciosos, restaurando la\l"
    .string "paz en el encinar.”\p"
    .string "“Desde entonces, Valiente y su\n"
    .string "entrenador compartieron muchas\l"
    .string "aventuras, enfrentando juntos la\l"
    .string "oscuridad y el miedo.”$"

LavenderTown_House2_Text_Inspector_Historia_Celebi::
    .string "“Hace siglos, en un encinar\n"
    .string "misterioso, un joven humano\l"
    .string "encontró a Celebi, el guardián del\l"
    .string "bosque.”\p"
    .string "“Con poderes para viajar en el\n"
    .string "tiempo, Celebi había quedado\l"
    .string "atrapado en una época oscura,\l"
    .string "rodeado de espíritus atormentados.”\p"
    .string "“El joven, compasivo y valiente,\n"
    .string "ayudó a Celebi a ahuyentar a los\l"
    .string "espíritus con su amistad y coraje.”\p"
    .string "“En agradecimiento, Celebi se\n"
    .string "convirtió en el compañero eterno\l"
    .string "del humano, acompañándolo a casa.”\p"
    .string "“Juntos, llevaron la magia del\n"
    .string "bosque a su aldea, trayendo\l"
    .string "prosperidad y esperanza.”\p"
    .string "“La leyenda de Celebi y el humano\n"
    .string "sigue siendo un cuento de unidad y\l"
    .string "amistad, un recordatorio de que la\l"
    .string "ayuda mutua puede superar la\l"
    .string "oscuridad.”$"

LavenderTown_House2_Text_Inspector_3::
    .string "Para que luego digan que los motes\n"
    .string "son una tontería, ¿eh?\p"
    .string "Te voy a contar otra leyenda:$"

LavenderTown_House2_Text_Inspector_4::
    .string "Las almas nobles siempre son\n"
    .string "recompensadas, recuérdalo.$"

LavenderTown_House2_Text_Inspector_5::
    .string "¡Guaau!\n"
    .string "¿Qué es esa luz?$"

LavenderTown_House2_Text_Inspector_6::
    .string "Ayuda…\n"
    .string "Fantasmas…$"

LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Hello, hello!\n"
    .string "I am the official NAME RATER!\p"
    .string "Want me to rate the nicknames of\n"
    .string "your POKéMON?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Which POKéMON's nickname should\n"
    .string "I critique?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a decent nickname!\p"
    .string "But, would you like me to give it\n"
    .string "a nicer name?\p"
    .string "How about it?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Ah, good. Then, what shall the new\n"
    .string "nickname be?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It is a better name than before!\n"
    .string "How fortunate for you!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "I see.\n"
    .string "Do come visit again.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It looks no different from before,\n"
    .string "and yet, this is vastly superior!\p"
    .string "How fortunate for you!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a truly impeccable name!\p"
    .string "Take good care of {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Now, now.\n"
    .string "That is merely an EGG!$"

