PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "La Torre Pokémon se erigió en\n"
    .string "memoria de los Pokémon fallecidos.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Esta Torre suele ser un lugar de\n"
    .string "calma y sosiego.\p"
    .string "Me inquieta que esa sensación haya\n"
    .string "desaparecido.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "girl.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Vi cómo los espíritus arrastraron\n"
    .string "hasta aquí a mi pobre CLEFAIRY.\p"
    .string "¡Sniff!\n"
    .string "Tengo tanto miedo e impotencia…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Se han llevado a mi GROWLITHE…\n"
    .string "¿Por qué?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Me encargo de proteger la Torre.\n"
    .string "Los espíritus están descontrolados.\p"
    .string "Noto la presencia del Sr. Fuji\n"
    .string "En lo más alto de la Torre.$"

