PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "La Torre Pokémon se erigió en\n"
    .string "memoria de los Pokémon fallecidos.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "son.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "girl.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "I came to pray for my dearly\n"
    .string "departed CLEFAIRY.\p"
    .string "Sniff!\n"
    .string "I'm awash in tears…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Se han llevado a mi GROWLITHE…\n"
    .string "¿Por qué?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Me encargo de proteger la torre.\p"
    .string "Los espíritus están descontrolados.\n"
    .string "El Sr. Fuji ha subido a calmarlos.$"

