RuinsOfAlph_Office_Text_PC::
    .string "RUINAS ALFA\n"
    .string "25 años de exploración.$"

RuinsOfAlph_Office_Text_Scientist_1::
    .string "Sabíamos que habían POKÉMON en las\n"
    .string "RUINAS, pero lo que está pasando\l"
    .string "nunca había ocurrido hasta ahora.\p"
    .string "Tus POKÉMON parecen cansados.\n"
    .string "¿Quieres descansar aquí un rato?$"

RuinsOfAlph_Office_Text_Scientist_2::
    .string "¿Los POKÉMON raros que viste en\n"
    .string "las RUINAS?\p"
    .string "Son muy parecidos a los dibujos de\n"
    .string "esas paredes de ahí.$"

RuinsOfAlph_Office_Text_Machine::
    .string "Esta máquina sirve para imprimir\n"
    .string "fotos de tu equipo en la FICHA DE\l"
    .string "ENTRENADOR.\p"
    .string "¿Quieres usarla?$"