PalletTown_Text_OakDontGoOut::
    .string "OAK: Hey! Wait!\n"
    .string "Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: It's unsafe!\n"
    .string "Wild POKéMON live in tall grass!\p"
    .string "You need your own POKéMON for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

PalletTown_Text_RaisingMonsToo::
    .string "I'm raising POKéMON, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

PalletTown_Text_Mistico_Introduccion::
    .string "Saludos, disculpa mi repentina\n"
    .string "aparición.\p"
    .string "No tengo tiempo para\n"
    .string "presentaciones.\p"
    .string "Provengo de un lugar que ha sido\n"
    .string "tomado por los espíritus.\p"
    .string "La providencia me ha traído\n"
    .string "hasta aquí en busca de alguien\l"
    .string "capaz de librarnos de ellos.$"

PalletTown_Text_Mistico_Pregunta::
    .string "Es cuestión de vida o muerte.\n"
    .string "¿Me ayudarás?$"

PalletTown_Text_Mistico_Teleport::
    .string "Ven, te llevaré a mi hogar.$"

PalletTown_Text_Mistico_Teleport_2::
    .string "Me temo que no tienes opción,\n"
    .string "lo harás igualmente.$"

